ALTER TABLE parties
  ADD COLUMN IF NOT EXISTS slug TEXT,
  ADD COLUMN IF NOT EXISTS tse_number INTEGER,
  ADD COLUMN IF NOT EXISTS full_name TEXT,
  ADD COLUMN IF NOT EXISTS website TEXT,
  ADD COLUMN IF NOT EXISTS ideology TEXT,
  ADD COLUMN IF NOT EXISTS foundation_year INTEGER,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS logo_url TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS parties_slug_idx ON parties(slug) WHERE slug IS NOT NULL;
